<a href="https://colab.research.google.com/github/Renukadevi-03/DS_Uber-Eats-Bangalore-Restaurant-Intelligence-Decision/blob/main/Capstone_project_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("/content/Uber_Eats_data.csv")

In [3]:
data.head()

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari

In [4]:
data.shape

(23193, 13)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23193 entries, 0 to 23192
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         23193 non-null  object
 1   online_order                 23193 non-null  object
 2   book_table                   23193 non-null  object
 3   rate                         23193 non-null  object
 4   votes                        23193 non-null  int64
 5   phone                        23193 non-null  object
 6   location                     23193 non-null  object
 7   rest_type                    23193 non-null  object
 8   dish_liked                   23193 non-null  object
 9   cuisines                     23193 non-null  object
 10  approx_cost(for two people)  23193 non-null  object
 11  listed_in(type)              23193 non-null  object
 12  listed_in(city)              23193 non-null  object
dtypes: int64(1), object(12)
memory usage: 2.3+ MB

In [6]:
data.describe()

              votes
count  23193.000000
mean     601.074462
std     1114.854301
min        0.000000
25%      101.000000
50%      221.000000
75%      586.000000
max    16832.000000

In [7]:
data.isnull().sum()

name                           0
online_order                   0
book_table                     0
rate                           0
votes                          0
phone                          0
location                       0
rest_type                      0
dish_liked                     0
cuisines                       0
approx_cost(for two people)    0
listed_in(type)                0
listed_in(city)                0
dtype: int64

In [8]:
duplicates = data[data.duplicated(subset=['name', 'location'], keep=False)]
duplicates.sort_values(by=['name', 'location'])

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
4405,#L-81 Cafe,Yes,No,3.9/5,48,+91 9986210891,HSR,Quick Bites,Burgers,"Fast Food, Beverages",400,Delivery,BTM
4824,#L-81 Cafe,Yes,No,3.9/5,48,+91 9986210891,HSR,Quick Bites,Burgers,"Fast Food, Beverages",400,Dine-out,BTM
7194,#L-81 Cafe,Yes,No,3.9/5,48,+91 9986210891,HSR,Quick Bites,Burgers,"Fast Food, Beverages",400,Delivery,HSR
7471,#L-81 Cafe,Yes,No,3.9/5,48,+91 9986210891,HSR,Quick Bites,Burgers,"Fast Food, Beverages",400,Dine-out,HSR
12281,#L-81 Cafe,Yes,No,3.9/5,48,+91 9986210891,HSR,Quick Bites,Burgers,"Fast Food, Beverages",400,Delivery,Koramangala 4th Block
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22665,nu.tree,Yes,No,4.3 /5,185,00 08310393035,Whitefield,"Quick Bites, Beverage Shop","Healthy Breakfast, Kadhi, Sprout Salad, Rajma ...","North Indian, Healthy Food, Beverages",400,Delivery,Whitefield
23085,nu.tree,Yes,No,4.2 /5,52,+91 8310393035,Whitefield,Quick Bites,"Palak Paneer, Idli, Aloo Paratha, Rajma Chawal...","North Indian, Healthy Food, Beverages",400,Dine-out,Whitefield
12774,re:cess - Hilton Bangalore Embassy GolfLinks,No,Yes,4.1 /5,146,080 66799999\r\r\n+91 7353759841,Domlur,"Casual Dining, Bar","Coffee, Cheesecake, Paratha, Hot Chocolate, Bi...","South Indian, North Indian, Continental, European","1,200",Dine-out,Koramangala 4th Block
20765,re:cess - Hilton Bangalore Embassy GolfLinks,No,Yes,4.1 /5,146,080 66799999\n+91 7353759841,Domlur,"Casual Dining, Bar","Coffee, Cheesecake, Paratha, Hot Chocolate, Bi...","South Indian, North Indian, Continental, European","1,200",Dine-out,Old Airport Road
20843,re:cess - Hilton Bangalore Embassy GolfLinks,No,Yes,4.1 /5,146,080 66799999\n+91 7353759841,Domlur,"Casual Dining, Bar","Coffee, Cheesecake, Paratha, Hot Chocolate, Bi...","South Indian, North Indian, Continental, European","1,200",Pubs and bars,Old Airport Road

In [9]:
data = data.drop_duplicates()

In [10]:
data.shape

(23158, 13)

In [11]:
data['rate'] = data['rate'].astype(str).str.extract(r'(\d+\.?\d*)')
data['rate'] = data['rate'].astype(float)

In [12]:
data['rate'].dtype

dtype('float64')

In [13]:
data['approx_cost(for two people)'] = data['approx_cost(for two people)'].astype(str).str.replace('₹', '')
data['approx_cost(for two people)'] = data['approx_cost(for two people)'].str.replace(',', '')
data['approx_cost(for two people)'] = data['approx_cost(for two people)'].astype(float)

In [14]:
data.rename(columns={
    'rate': 'rating',
    'approx_cost(for two people)': 'cost',
}, inplace=True)

In [15]:
data.to_csv("cleaned_uber_eats_data.csv", index=False)

In [16]:
from google.colab import files
files.download("cleaned_uber_eats_data.csv")